# docker‑compose.yml
version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "${DB_PORT}:3306" # 호스트(DB_PORT) ↔ 컨테이너(3306)
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: . # 이 디렉토리(backend)의 Dockerfile 사용
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000" # 호스트 3000 ↔ 컨테이너 3000
    env_file:
      - .env # DB_HOST 등 환경변수 로드
    environment:
      DB_HOST: db # 컨테이너 네트워크 상의 DB 서비스명
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db_data:
