# backend/docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=chat-db.c09w0ei8ggyp.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_USERNAME=jiheon
      - DB_PASSWORD=AA123456789
      - DB_DATABASE=chat_db
      - PORT=3000
      - CORS_ORIGIN=https://open-chat-sandy.vercel.app
